### ISSUE TITLE
Notebook 3a: Tabular Data: BnDropLin -> LinBnDrop

### ISSUE THREAD

**Issue by takotab** [muellerzr/Practical-Deep-Learning-for-Coders-2.0#1]
Notebook 3a: Tabular Data does not run any more in the TabularModel you use BnDropLin. This probaly has moved it is now in local.layers and called LinBnDrop.

No worries. Thanks for putting this stuff out there.

**Comment by muellerzr** [comment]
It’s because they redid most of tabular data. I’ll fix it this week. Thanks!

**Comment by muellerzr** [comment]
I'm uploading a changed 3a notebook momentarily where instead we just call from `fastai2.tabular.model` (since now we can)
