### ISSUE TITLE
default path is a hidden folder

### ISSUE THREAD

**Issue by marcNY** [muellerzr/Practical-Deep-Learning-for-Coders-2.0#15]
When using the untar_data function by default the data are downloaded In ~/.fastai/data
I think it creates issues to have these data downloaded in a hidden folder for beginners because we cannot find the data using the explorer and this creates a massive hidden folder.

**Comment by muellerzr** [comment]
You can simply pass in a destination folder into `untar_data` for that to happen. IE `dest='/myDir'`. I'm not going to go back and add this in however as users that want to look at that direct view can go look at the documentation or source, something I've said quite a number of times in the walkthroughs.
