### ISSUE TITLE
emb_drop is not a parameter of tabular_learner

### ISSUE THREAD

**Issue by rubensmau** [muellerzr/Practical-Deep-Learning-for-Coders-2.0#16]
In the  current version of fastai2 , emb_drop is not a parameter of tabular_learner.
This parameter needs to be removed from 02_Bayesian_Optimization.ipynb

**Comment by waydegg** [comment]
Additionally `ps` and `emb_p` are not parameters anymore either. I guess they've been removed/renamed in a recent fastai2 update?

**Comment by waydegg** [comment]
Nevermind, see [this post](https://forums.fast.ai/t/a-walk-with-fastai2-tabular-study-group-and-online-lectures-megathread/64361/101?u=waydegg). Basically you pass in a `tabular_config` to your learner, and several of the parameters like `ps` and emb_p` are in this config object.

**Comment by muellerzr** [comment]
I've fixed this
