### ISSUE TITLE
Changing header columns in df gives error while forming lm dataloader

### ISSUE THREAD

**Issue by anindabitm** [muellerzr/Practical-Deep-Learning-for-Coders-2.0#18]
This is my first time. So please forgive me if this is totally wrong.
[Copy_of_01_Intro.zip](https://github.com/muellerzr/Practical-Deep-Learning-for-Coders-2.0/files/4545649/Copy_of_01_Intro.zip)

I faced an issue with fastai2 text module. If I change the name of the columns of the imdb dataframe from
['label','text','is_valid'] to ['['label','safe_text','valid_or_not'] using df.columns = df.columns=['label','safe_text','valid_or_not']

Then if I run, 
imdb_lm = DataBlock(blocks=TextBlock.from_df('safe_text', is_lm=True),
                    get_x=ColReader('safe_text'),
                    splitter=RandomSplitter(0.1))

dls = imdb_lm.dataloaders(df, bs=64, seq_len=72)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-bc99acb44dee> in <module>()
----> 1 dls = imdb_lm.dataloaders(df, bs=64, seq_len=72)

13 frames
/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py in __getattr__(self, name)
   5272             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5273                 return self[name]
-> 5274             return object.__getattribute__(self, name)
   5275 
   5276     def __setattr__(self, name: str, value) -> None:

AttributeError: 'Series' object has no attribute 'safe_text'

Changing the column names is giving an error while trying to build the dataloader

**Comment by muellerzr** [comment]
Your get_x should always be ‘text’, as when tokenizing this is changed

**Comment by anindabitm** [comment]
Thanks a lot for your quick reply
