### ISSUE TITLE
04_TabNet run error

### ISSUE THREAD

**Issue by adriangrepo** [muellerzr/Practical-Deep-Learning-for-Coders-2.0#24]
Process:
Create new virtualenv, install jupyter
Run 04_TabNet 
At g just after after Graph heading I get following error:

FileNotFoundError                         Traceback (most recent call last)
~/.virtualenvs/pdlfc2/lib/python3.6/site-packages/pydot.py in create(self, prog, format, encoding)
   1914                 arguments=arguments,
-> 1915                 working_dir=tmp_dir,
   1916             )

~/.virtualenvs/pdlfc2/lib/python3.6/site-packages/pydot.py in call_graphviz(program, arguments, working_dir, **kwargs)
    135         stdout=subprocess.PIPE,
--> 136         **kwargs
    137     )

/usr/lib/python3.6/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    728                                 errread, errwrite,
--> 729                                 restore_signals, start_new_session)
    730         except:

/usr/lib/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1363                             err_msg += ': ' + repr(err_filename)
-> 1364                     raise child_exception_type(errno_num, err_msg, err_filename)
   1365                 raise child_exception_type(err_msg)

FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

also the line 2 cells after Hide:

feat_tfmer = [*shared, *specifics]

> shared has not been defined at that stage.

**Comment by adriangrepo** [comment]
Can fix first issue by installing fastaiv2 as per fastai github workflow then running code above (rather than just pip install into a fresh venv).

fast_tabnet has been updated. the following in TabNetModel will no longer work:

x, m_loss, m_explain, masks = self.tab_net(x)

Need to split this into two calls on the TabNetNoEmbeddings object. Sorry havent had time to do pull request to fix.

**Comment by muellerzr** [comment]
I've pinned the version back to when it works.
