### ISSUE TITLE
Much time for ShapInterpretation

### ISSUE THREAD

**Issue by henry090** [muellerzr/Practical-Deep-Learning-for-Coders-2.0#36]
Hi. Thanks for the interesting and useful notebooks. However, why ShapInterpretation requires a lot of time for processing? For example, for the Adult dataset? And is this the expected behavior?

```
34%|███▎      | 43/128 [06:01<11:53,  8.39s/it]
```

**Comment by muellerzr** [comment]
Yes, SHAP is not a very fast process, hence why the example did not use many values.

**Comment by henry090** [comment]
Thanks, Zachary!
