### ISSUE TITLE
Typo in 01_pets notebook

### ISSUE THREAD

**Issue by Kshitij09** [muellerzr/Practical-Deep-Learning-for-Coders-2.0#5]
In [01_pets.ipynb](https://github.com/muellerzr/Practical-Deep-Learning-for-Coders-2.0/blob/master/Computer%20Vision/01_Pets.ipynb),

`ImageDataLoader` should be `ImageDataLoaders`. I know it's a trivial issue but this typo causes "name not defined" error.

**Comment by muellerzr** [comment]
Thanks! I appreciate the flag, it’s hard for me to go back and adjust everything with the API changes so thanks for flagging this :) I’ll make this adjustment here when I can

**Comment by Kshitij09** [comment]
I'll be going through your notebooks in effort to learn fastai2. Will report an issue if I notice anything has been changed, will that be fine?

Also, I could submit a PR for this fix.

**Comment by muellerzr** [comment]
Both would be fantastic if possible! That’s why I made this repo / study group 😊

**Comment by flydragon2018** [comment]
which fastai version It is ?

two much confusion about  ImageDatabunch and ImageDataLoaders
